server:
  port: 80
  servlet:
    context-path: /
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/familytree?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
      username: family
      password: family
      driverClassName: com.mysql.jdbc.Driver
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false  
  session:
    timeout: 3600
    jdbc:
      schema: schema-mysql.sql
    store-type: jdbc
  jpa:
    hibernate:
      ddl-auto: none
security:
  oauth2: 
    client: 
      client-id: family_tree
      client-secret: family_tree
      access-token-uri: http://localhost/oauth/token
      user-authorization-uri: http://localhost/oauth/authorize
    resource:
      user-info-uri: http://localhost/user/me

logging:
  level: 
    org.springframework.security: DEBUG

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
